import * as numbers from "./SchemaNumber";
import {SchemaText} from "./SchemaText";
import {SchemaBool} from "./SchemaBool";
import {SchemaDate} from "./SchemaDate";
import {SchemaTextArray} from "./SchemaTextArray";
import {SchemaJSON} from "./SchemaJSON";
import {SchemaIdArray} from "./SchemaIdArray";
import {SchemaNumArray} from "./SchemaNumArray";
import {SchemaId} from "./SchemaId";
import {SchemaHtml} from "./SchemaHtml";

export var NumberType = numbers.NumberType;
export var num = numbers.SchemaNumber;
export var text = SchemaText;
export var textArray = SchemaTextArray;
export var json = SchemaJSON;
export var idArray = SchemaIdArray;
export var numArray = SchemaNumArray;
export var date = SchemaDate;
export var bool = SchemaBool;
export var id = SchemaId;
export var html = SchemaHtml;