import * as numbers from './schema-number';
import { SchemaText } from './schema-text';
import { SchemaBool } from './schema-bool';
import { SchemaDate } from './schema-date';
import { SchemaTextArray } from './schema-text-array';
import { SchemaJSON } from './schema-json';
import { SchemaIdArray } from './schema-id-array';
import { SchemaNumArray } from './schema-num-array';
import { SchemaId } from './schema-id';
import { SchemaHtml } from './schema-html';
import { SchemaForeignKey } from './schema-foreign-key';

export const NumberType = numbers.NumberType;
export const num = numbers.SchemaNumber;
export const text = SchemaText;
export const textArray = SchemaTextArray;
export const json = SchemaJSON;
export const idArray = SchemaIdArray;
export const numArray = SchemaNumArray;
export const date = SchemaDate;
export const bool = SchemaBool;
export const id = SchemaId;
export const html = SchemaHtml;
export const foreignKey = SchemaForeignKey;